/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Reservation;

/**
 *
 * @author namw2
 */
public class ReservationCheckView extends javax.swing.JFrame {

    //TODO nsw: 새로운 기능 만들어야할거
    // 1. txt파일 읽어와서 파싱해가지고 값 분리
    // 2. 콤보박스 선택한거에 따라 만들기
    // 3. 현재 날짜 가져오서 과거의 날짜 선택 불가하게 만들기
    /**
     * /**
     * Creates new form ReservationCheckView
     */
    public ReservationCheckView() {
        initComponents();

        initCustomLogic();
    }

    private void initCustomLogic() {
        // 1. 초기 룸 타입에 맞춰 룸 번호 설정 (처음 켜졌을 때)
        updateRoomNumbers();
        updateYMD();

        java.awt.event.ActionListener dateListener = new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateYMD(); // 년, 월, 일 중 하나라도 바뀌면 실행
            }
        };

        // 만든 리스너를 3개의 콤보박스에 모두 등록
        Year.addActionListener(dateListener);
        Month.addActionListener(dateListener);
        Day.addActionListener(dateListener);

// 2. RoomType(강의실/실습실) 변경 시 이벤트 발생 -> RoomNum 목록 변경
        RoomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRoomNumbers(); // 선택된 타입에 따라 번호 갱신 함수 호출

            }
        });

        RoomNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // RoomNum이 비워지는 순간(removeAllItems) 에러 방지용 null 체크
                if (RoomNum.getSelectedItem() != null) {
                    selectedRoom.setText((String) RoomNum.getSelectedItem());
                }
            }
        });
        // (선택 사항) 현재 날짜로 콤보박스 초기값 설정하는 로직을 여기에 넣을 수 있습니다.
    }
    
    // [중요] 컨트롤러에서 테이블을 직접 건드리기 위해 필요

    public javax.swing.JTable getTimeTable() {
        return TimeTable;
    }

    // [중요] 이벤트 리스너 등록 메서드들 (컨트롤러에서 사용)
    public void addDateChangeListener(java.awt.event.ActionListener listener) {
        Year.addActionListener(listener);
        Month.addActionListener(listener);
        Day.addActionListener(listener);
    }

    public void addRoomTypeChangeListener(java.awt.event.ActionListener listener) {
        RoomType.addActionListener(listener);
    }

    public void addRoomNumChangeListener(java.awt.event.ActionListener listener) {
        RoomNum.addActionListener(listener);
    }
    // [기능 2] 룸 타입에 따라 룸 번호 콤보박스 내용을 바꾸는 메서드
    private void updateRoomNumbers() {
        String selectedType = (String) RoomType.getSelectedItem();

        // 기존 항목 싹 지우기 (초기화)
        RoomNum.removeAllItems();

        if ("강의실".equals(selectedType)) {
            // 강의실일 경우의 목록
            String[] classrooms = {"911", "912", "913"};
            for (String room : classrooms) {
                RoomNum.addItem(room);
            }
        } else if ("실습실".equals(selectedType)) {
            // 실습실일 경우의 목록
            String[] labs = {"914", "915", "916"};
            for (String room : labs) {
                RoomNum.addItem(room);
            }
        } else {
            // "전체" 또는 선택 안됨일 경우 모든 방 표시
            String[] allRooms = {"911", "912", "913", "914", "915", "916", "918"};
            for (String room : allRooms) {
                RoomNum.addItem(room);
            }
        }

        selectedRoom.setText((String) RoomNum.getSelectedItem());

    }

    private void updateYMD() {
        selectedYMD.setText(getSelectedDate());
    }
    
    private void updateTimeTable(){
    
    
    }

    // [기능 3] 외부(Controller)에서 선택된 값들을 가져오기 위한 Getter 메서드들
    // 1. 선택된 날짜 문자열로 합쳐서 반환 (예: "2025-11-23")
    public String getSelectedDate() {
        String y = (String) Year.getSelectedItem();
        String m = (String) Month.getSelectedItem();
        String d = (String) Day.getSelectedItem();

        // 월, 일이 한 자리 수일 경우 0 붙이기 (선택 사항)
        if (m.length() == 1) {
            m = "0" + m;
        }
        if (d.length() == 1) {
            d = "0" + d;
        }

        return y + "-" + m + "-" + d;
    }

    public String getSelectedRoomType() {
        return (String) RoomType.getSelectedItem();
    }

    public String getSelectedRoomNum() {
        return (String) RoomNum.getSelectedItem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        goback = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TimeTable = new javax.swing.JTable();
        Year = new javax.swing.JComboBox<>();
        RoomType = new javax.swing.JComboBox<>();
        Month = new javax.swing.JComboBox<>();
        Day = new javax.swing.JComboBox<>();
        RoomNum = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        selectedRoom = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        selectedYMD = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        jLabel1.setText("예약 현황 조회");

        goback.setText("뒤로가기");

        TimeTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TimeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"09:00~09:50", null, null, null, null, null, null, null},
                {"10:00~10:50", null, null, null, null, null, null, null},
                {"11:00~11:50", null, null, null, null, null, null, null},
                {"12:00~12:50", null, null, null, null, null, null, null},
                {"13:00~13:50", null, null, null, null, null, null, null},
                {"14:00~14:50", null, null, null, null, null, null, null},
                {"15:00~15:50", null, null, null, null, null, null, null},
                {"16:00~16:50", null, null, null, null, null, null, null},
                {"17:00~17:50", null, null, null, null, null, null, null},
                {"18:00~18:50", null, null, null, null, null, null, null},
                {"19:00~19:50", null, null, null, null, null, null, null},
                {"20:00~20:50", null, null, null, null, null, null, null},
                {"21:00~21:50", null, null, null, null, null, null, null}
            },
            new String [] {
                "시간", "월", "화", "수", "목", "금", "토", "일"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TimeTable.setAlignmentX(1.0F);
        TimeTable.setAlignmentY(1.0F);
        jScrollPane1.setViewportView(TimeTable);

        Year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2025", "2026", "2027" }));

        RoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "전체", "강의실", "실습실" }));

        Month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        Day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));

        RoomNum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "911", "912", "913", "914", "915", "916" }));

        jLabel2.setText("선택한 강의실 : ");

        selectedRoom.setText("jLabel2");

        jLabel4.setText("선택한 날짜 : ");

        selectedYMD.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(goback))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RoomNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(selectedRoom, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(selectedYMD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(goback)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RoomNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(selectedRoom, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(selectedYMD, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // ReservationCheckView 클래스 내부에 추가
    public void addGoBackListener(java.awt.event.ActionListener listener) {
        goback.addActionListener(listener);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservationCheckView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservationCheckView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservationCheckView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservationCheckView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservationCheckView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Day;
    private javax.swing.JComboBox<String> Month;
    private javax.swing.JComboBox<String> RoomNum;
    private javax.swing.JComboBox<String> RoomType;
    private javax.swing.JTable TimeTable;
    private javax.swing.JComboBox<String> Year;
    private javax.swing.JButton goback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel selectedRoom;
    private javax.swing.JLabel selectedYMD;
    // End of variables declaration//GEN-END:variables
}
