/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deu.hms.login;
import javax.swing.JFrame;

/**
 *
 * @author yunhe
 */
public class MainScreenEmployees extends javax.swing.JFrame {
    
    
    private UserAuthentication auth;

        public MainScreenEmployees() {
        setTitle("Employee Main Screen");
        setSize(600, 400);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setTitle("메인화면");

    }

    private Object deu;

    /**
     * Creates new form MainScreenEmployees
     */
    public MainScreenEmployees(UserAuthentication auth) {
        this.auth = auth;  // 로그인 인증 객체를 생성자로 전달받음
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        goReservationEmployees = new javax.swing.JButton();
        goCheckoutEmployees = new javax.swing.JButton();
        goRoomserviceEmployees = new javax.swing.JButton();
        goRestaurantEmployees = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        goCheckinEmployees = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        goReservationEmployees.setText("예약 관리");
        goReservationEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goReservationEmployeesActionPerformed(evt);
            }
        });

        goCheckoutEmployees.setText("체크아웃");
        goCheckoutEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goCheckoutEmployeesActionPerformed(evt);
            }
        });

        goRoomserviceEmployees.setText("룸서비스");
        goRoomserviceEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goRoomserviceEmployeesActionPerformed(evt);
            }
        });

        goRestaurantEmployees.setText("레스토랑");
        goRestaurantEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goRestaurantEmployeesActionPerformed(evt);
            }
        });

        logoutButton.setText("out");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        goCheckinEmployees.setText("체크인");
        goCheckinEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goCheckinEmployeesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(goRoomserviceEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(goRestaurantEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(goCheckinEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(goCheckoutEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(goReservationEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(goReservationEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(goCheckoutEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(goCheckinEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(goRoomserviceEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(goRestaurantEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goReservationEmployeesActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        deu.hms.reservation.reservationFrame reservationFrame = new deu.hms.reservation.reservationFrame(new java.awt.Frame(), true);
        
        reservationFrame.repaint();     // 업데이트된 상태를 반영하여 다시 그리기

        reservationFrame.setLocationRelativeTo(null);  // 화면 가운데 배치
        reservationFrame.setVisible(true);
        }                                                 

    private void goCheckoutEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goCheckoutEmployeesActionPerformed
    //checkout  checkoutFrame = new checkout(this);
    deu.hms.checkout.checkout checkoutFrame = new deu.hms.checkout.checkout();
    checkoutFrame.setLocationRelativeTo(null);  // 화면 가운데 배치
    checkoutFrame.setVisible(true);
    }//GEN-LAST:event_goCheckoutEmployeesActionPerformed

    private void goRoomserviceEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goRoomserviceEmployeesActionPerformed
        deu.hms.roomservice.roomserviceFrame roomserviceFrame = new deu.hms.roomservice.roomserviceFrame(new java.awt.Frame(), true);
        roomserviceFrame.setLocationRelativeTo(null);  // 화면 가운데 배치
        roomserviceFrame.setVisible(true);
    }//GEN-LAST:event_goRoomserviceEmployeesActionPerformed

    private void goRestaurantEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goRestaurantEmployeesActionPerformed
        deu.hms.restaurant.restaurantFrame restaurantFrame = new deu.hms.restaurant.restaurantFrame(new java.awt.Frame(), true);
        restaurantFrame.setLocationRelativeTo(null);  // 화면 가운데 배치
        restaurantFrame.setVisible(true);
    }//GEN-LAST:event_goRestaurantEmployeesActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // 로그아웃 처리
        auth.logout();  // UserAuthentication 객체에서 로그아웃 처리
        
        // MainScreenManager 창 닫기
        this.dispose();  // 현재 창 (MainScreenManager) 닫기
        
        // 로그인 창으로 돌아가기
        loginFrame loginScreen = new loginFrame(auth); // 로그인 화면 생성
        loginScreen.setLocationRelativeTo(null);  // 화면 중앙에 배치
        loginScreen.setVisible(true);  // 로그인 화면 표시

        // MainScreenManager 창 닫기
        this.dispose();  // 현재 창 (MainScreenManager) 닫기
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void goCheckinEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goCheckinEmployeesActionPerformed
        // CheckInUI 인스턴스를 기본 생성자를 사용해 생성합니다.
        deu.hms.checkin.CheckInUI checkinFrame = new deu.hms.checkin.CheckInUI();
        checkinFrame.setLocationRelativeTo(null);  // 화면 가운데 배치
        checkinFrame.setVisible(true);
    }//GEN-LAST:event_goCheckinEmployeesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton goCheckinEmployees;
    private javax.swing.JButton goCheckoutEmployees;
    private javax.swing.JButton goReservationEmployees;
    private javax.swing.JButton goRestaurantEmployees;
    private javax.swing.JButton goRoomserviceEmployees;
    private javax.swing.JButton logoutButton;
    // End of variables declaration//GEN-END:variables
}
