/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package deu.hms.management;

import deu.hms.login.MainScreenEmployees;
import deu.hms.login.MainScreenManager;
import deu.hms.login.UserAuthentication;
import deu.hms.roomManagement.RoomService;  // RoomService 임포트
import deu.hms.roomManagement.RoomManagementFrame;  // RoomManagementFrame 임포트
import deu.hms.restaurantManagement.restaurantManagementFrame;
import deu.hms.roomManagement.RoomRepository;

/**
 *
 * @author Jimin
 */
public class managementFrame extends javax.swing.JDialog {

    private Object deu;

    /**
     * Creates new form managementFrame
     * @param parent
     * @param modal
     */
    public managementFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userInfoButton = new javax.swing.JButton();
        roomInfoButton = new javax.swing.JButton();
        restButton = new javax.swing.JButton();
        hotelInfo = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        userInfoButton.setText("계정 관리");
        userInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userInfoButtonActionPerformed(evt);
            }
        });

        roomInfoButton.setText("객실 관리");
        roomInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomInfoButtonActionPerformed(evt);
            }
        });

        restButton.setText("식당 관리");
        restButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restButtonActionPerformed(evt);
            }
        });

        hotelInfo.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        hotelInfo.setText("호텔 정보");

        backButton.setText("<");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roomInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hotelInfo)
                            .addComponent(restButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hotelInfo)
                .addGap(30, 30, 30)
                .addComponent(roomInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(restButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(userInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userInfoButtonActionPerformed
        deu.hms.userManagement.userManagementFrame usermanagementframe = new deu.hms.userManagement.userManagementFrame();
        usermanagementframe.setLocationRelativeTo(null);
        usermanagementframe.setVisible(true);
       this.dispose();  // 현재 창 닫기
      
       
    }//GEN-LAST:event_userInfoButtonActionPerformed

    private void roomInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomInfoButtonActionPerformed
    // RoomService 객체를 준비합니다.
    RoomService roomService = new RoomService(new RoomRepository());

    // RoomManagementFrame을 생성하고 표시합니다.
    RoomManagementFrame roomManagementFrame = new RoomManagementFrame(roomService);
    this.dispose();
    roomManagementFrame.setVisible(true); // 화면에 표시
    }//GEN-LAST:event_roomInfoButtonActionPerformed

    private void restButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restButtonActionPerformed
        deu.hms.restaurantManagement.restaurantManagementFrame restmanagementframe = new deu.hms.restaurantManagement.restaurantManagementFrame(null, true);
        this.dispose();  // 현재 창 닫기
        // RoomManagementFrame을 현재 창 위에 띄움
        restmanagementframe.setVisible(true);
    }//GEN-LAST:event_restButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
            // 현재 창을 닫고 MainScreenManager로 이동
        this.dispose();  // userManagementFrame 닫기

        // UserAuthentication 객체 생성 (예시: 로그인 정보를 사용)
        UserAuthentication userAuth = new UserAuthentication();

        // MainScreenManager로 이동, UserAuthentication 객체 전달
        MainScreenManager mainScreenManager = new MainScreenManager(userAuth);
        mainScreenManager.setLocationRelativeTo(null);  // 화면 가운데 배치
        mainScreenManager.setVisible(true);  // MainScreenManager 창을 표시
    }//GEN-LAST:event_backButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel hotelInfo;
    private javax.swing.JButton restButton;
    private javax.swing.JButton roomInfoButton;
    private javax.swing.JButton userInfoButton;
    // End of variables declaration//GEN-END:variables
}
