/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deu.hms.userManagement;

import javax.swing.*;
import javax.swing.table.TableModel;

/**
 *
 * @author yunhe
 */
public class UserModify extends javax.swing.JFrame {
    
    private TableModel tableModel;
    private int selectedRow;
    
    /**
     * Creates new form UserModify
     */
    public UserModify(userManagementFrame parent, TableModel tableModel, int selectedRow) {
        this.tableModel = tableModel;
        this.selectedRow = selectedRow;

        setTitle("사용자 수정");
        initComponents();
        loadUserDataToFields();
        setLocationRelativeTo(null); // 창을 화면 중앙에 배치
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); // 창 닫기 동작 설정
    }
    
    private void loadUserDataToFields() {
        String userName = (String) tableModel.getValueAt(selectedRow, 2);
        String userId = (String) tableModel.getValueAt(selectedRow, 0);
        String userPassword = (String) tableModel.getValueAt(selectedRow, 1);
        String userRole = (String) tableModel.getValueAt(selectedRow, 3);

        // TextField 및 UI 컴포넌트에 값 설정
        inUserNameModify.setText(userName);
        inUserIDModify.setText(userId);
        inUserPWModify.setText(userPassword);

        // 권한(role)에 따라 체크박스를 설정
        if ("Employee".equalsIgnoreCase(userRole)) {
            pickEmployeeModify.setSelected(true);
            pickManagerModify.setSelected(false); // 반대 체크박스는 비활성화
        } else if ("Manager".equalsIgnoreCase(userRole)) {
            pickManagerModify.setSelected(true);
            pickEmployeeModify.setSelected(false); // 반대 체크박스는 비활성화
        } else {
            // 역할이 명확하지 않은 경우 체크박스 초기화
            pickEmployeeModify.setSelected(false);
            pickManagerModify.setSelected(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pickManagerModify = new javax.swing.JCheckBox();
        pwLabelModify = new java.awt.Label();
        inUserPWModify = new javax.swing.JTextField();
        inUserIDModify = new javax.swing.JTextField();
        inUserNameModify = new javax.swing.JTextField();
        nameLabelModify = new java.awt.Label();
        idLabelModify = new java.awt.Label();
        userModifyTitle = new java.awt.Label();
        saveButtonModify = new javax.swing.JButton();
        pickEmployeeModify = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pickManagerModify.setText("관리자");
        pickManagerModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickManagerModifyActionPerformed(evt);
            }
        });

        pwLabelModify.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        pwLabelModify.setText("비밀번호");

        inUserPWModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inUserPWModifyActionPerformed(evt);
            }
        });

        inUserIDModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inUserIDModifyActionPerformed(evt);
            }
        });

        inUserNameModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inUserNameModifyActionPerformed(evt);
            }
        });

        nameLabelModify.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        nameLabelModify.setText("이름");

        idLabelModify.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        idLabelModify.setText("아이디");

        userModifyTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        userModifyTitle.setText("사용자 수정");

        saveButtonModify.setText("저장");
        saveButtonModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonModifyActionPerformed(evt);
            }
        });

        pickEmployeeModify.setText("일반 직원");
        pickEmployeeModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickEmployeeModifyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButtonModify, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(pickManagerModify)
                                        .addGap(18, 18, 18)
                                        .addComponent(pickEmployeeModify))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(pwLabelModify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(idLabelModify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nameLabelModify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(inUserPWModify, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(inUserIDModify, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(inUserNameModify, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(userModifyTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 23, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(userModifyTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inUserNameModify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabelModify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inUserIDModify, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLabelModify, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inUserPWModify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwLabelModify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pickManagerModify)
                    .addComponent(pickEmployeeModify))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButtonModify)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pickManagerModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickManagerModifyActionPerformed
        if (pickManagerModify.isSelected()) {
            pickEmployeeModify.setEnabled(false);  // "직원" 체크박스를 비활성화
        } else {
            pickEmployeeModify.setEnabled(true);   // "직원" 체크박스를 활성화
        }
    }//GEN-LAST:event_pickManagerModifyActionPerformed

    private void inUserPWModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inUserPWModifyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inUserPWModifyActionPerformed

    private void inUserIDModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inUserIDModifyActionPerformed
        inUserPWModify.requestFocus();
    }//GEN-LAST:event_inUserIDModifyActionPerformed

    private void inUserNameModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inUserNameModifyActionPerformed
        inUserIDModify.requestFocus();
    }//GEN-LAST:event_inUserNameModifyActionPerformed

    private void saveButtonModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonModifyActionPerformed
        String name = inUserNameModify.getText();
        String id = inUserIDModify.getText();
        String password = inUserPWModify.getText();
        String role = pickEmployeeModify.isSelected() ? "Employee" : "Manager";
        
        // 수정된 정보를 TableModel에 업데이트
        tableModel.setValueAt(name, selectedRow, 2); // 이름
        tableModel.setValueAt(id, selectedRow, 0);   // 아이디
        tableModel.setValueAt(password, selectedRow, 1); // 비밀번호
        tableModel.setValueAt(role, selectedRow, 3); // 역할
        
        // UserModifyManager를 통해 저장 처리 (옵션)
        UserModifyManager.modifyUser(id, new User(id, password, name, role));
        
        // 저장 완료 메시지 출력
        JOptionPane.showMessageDialog(this, "사용자 정보가 수정되었습니다.", "저장 성공", JOptionPane.INFORMATION_MESSAGE);

        // 창 닫기
        dispose();
    
    }//GEN-LAST:event_saveButtonModifyActionPerformed

    private void pickEmployeeModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickEmployeeModifyActionPerformed
        if (pickEmployeeModify.isSelected()) {
            pickManagerModify.setEnabled(false);  // "관리자" 체크박스를 비활성화
        } else {
            pickManagerModify.setEnabled(true);   // "관리자" 체크박스를 활성화
        }
    }//GEN-LAST:event_pickEmployeeModifyActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                int selectedRow = userInfoTable.getSelectedRow();
                if (selectedRow == -1) {
                    JOptionPane.showMessageDialog(this, "수정할 사용자를 선택해주세요!", "오류", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                // 선택된 사용자 데이터를 전달하며 UserModify 호출
                UserModify modifyFrame = new UserModify(this, userInfoTable.getModel(), selectedRow);
                modifyFrame.setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label idLabelModify;
    private javax.swing.JTextField inUserIDModify;
    private javax.swing.JTextField inUserNameModify;
    private javax.swing.JTextField inUserPWModify;
    private java.awt.Label nameLabelModify;
    private javax.swing.JCheckBox pickEmployeeModify;
    private javax.swing.JCheckBox pickManagerModify;
    private java.awt.Label pwLabelModify;
    private javax.swing.JButton saveButtonModify;
    private java.awt.Label userModifyTitle;
    // End of variables declaration//GEN-END:variables
}
