/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deu.hms.userManagement;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import deu.hms.login.MainScreenManager;  // MainScreenManager를 import 합니다.
import deu.hms.login.UserAuthentication;


/**
 *
 * @author yunhe
 */
public class userManagementFrame extends javax.swing.JFrame {
    
    
    /**
     * Creates new form userManagementFrame1
     */
    public userManagementFrame() {
        
        setTitle("사용자 관리");
        
        initComponents();
        loadUserTableData(); // 프로그램 시작 시 테이블 데이터 로드
        setLocationRelativeTo(null); // 창을 화면 중앙에 배치
    }
    
    // JTable을 외부에서 접근할 수 있도록 메서드 추가
    public JTable getUserInfoTable() {
        return userInfoTable;
    }
    
     // users.txt의 데이터를 UserInfoTable에 로드
    private void loadUserTableData() {
        UserTableManager.loadUsersToTable(userInfoTable, "users.txt");
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userModifyButton = new javax.swing.JButton();
        userDeleteButton = new javax.swing.JButton();
        userAddButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        userInfoTableScrollPane = new javax.swing.JScrollPane();
        userInfoTable = new javax.swing.JTable();
        usertManagement = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userModifyButton.setText("수정");
        userModifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userModifyButtonActionPerformed(evt);
            }
        });

        userDeleteButton.setText("삭제");
        userDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userDeleteButtonActionPerformed(evt);
            }
        });

        userAddButton.setText("등록");
        userAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userAddButtonActionPerformed(evt);
            }
        });

        backButton.setText("<");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        userInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "아이디", "비밀번호", "이름", "권한"
            }
        ));
        userInfoTableScrollPane.setViewportView(userInfoTable);

        usertManagement.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        usertManagement.setText("사용자 관리");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(userAddButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userModifyButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(userDeleteButton))
                            .addComponent(userInfoTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addGap(131, 131, 131)
                        .addComponent(usertManagement)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton)
                    .addComponent(usertManagement))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userInfoTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userAddButton)
                    .addComponent(userDeleteButton)
                    .addComponent(userModifyButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userModifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userModifyButtonActionPerformed
        // UserManagementFrame에서 UserModify 호출 예시
        int selectedRow = userInfoTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "수정할 사용자를 선택해주세요!", "오류", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 선택된 사용자 데이터를 전달하며 UserModify 호출
        UserModify modifyFrame = new UserModify(this, userInfoTable.getModel(), selectedRow);
        modifyFrame.setVisible(true);
    }//GEN-LAST:event_userModifyButtonActionPerformed

    private void userDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userDeleteButtonActionPerformed
      int selectedRow = userInfoTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "삭제할 사용자를 선택해주세요!", "오류", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String id = (String) userInfoTable.getValueAt(selectedRow, 0);

        // 삭제 처리
        UserDeleteManager.deleteUser(id, "users.txt");
        System.out.println("사용자 삭제 성공: ");

        loadUserTableData(); // 테이블 갱신
        JOptionPane.showMessageDialog(this, "사용자가 삭제되었습니다.");
    }//GEN-LAST:event_userDeleteButtonActionPerformed

    private void userAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userAddButtonActionPerformed
       UserAdd userAdd = new UserAdd(this); // 현재 UserManagementFrame을 전달
       userAdd.setVisible(true);
    }//GEN-LAST:event_userAddButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
       // 현재 창을 닫고 MainScreenManager로 이동
        this.dispose();  // userManagementFrame 닫기

        // UserAuthentication 객체 생성 (예시: 로그인 정보를 사용)
        UserAuthentication userAuth = new UserAuthentication();

        // MainScreenManager로 이동, UserAuthentication 객체 전달
        MainScreenManager mainScreenManager = new MainScreenManager(userAuth);
        mainScreenManager.setLocationRelativeTo(null);  // 화면 가운데 배치
        mainScreenManager.setVisible(true);  // MainScreenManager 창을 표시
    }//GEN-LAST:event_backButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton userAddButton;
    private javax.swing.JButton userDeleteButton;
    private javax.swing.JTable userInfoTable;
    private javax.swing.JScrollPane userInfoTableScrollPane;
    private javax.swing.JButton userModifyButton;
    private javax.swing.JLabel usertManagement;
    // End of variables declaration//GEN-END:variables
}
